package com.example.delamey.myapplication5.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.delamey.myapplication5.bean.young;

import com.example.delamey.myapplication5.greendao.youngDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig youngDaoConfig;

    private final youngDao youngDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        youngDaoConfig = daoConfigMap.get(youngDao.class).clone();
        youngDaoConfig.initIdentityScope(type);

        youngDao = new youngDao(youngDaoConfig, this);

        registerDao(young.class, youngDao);
    }
    
    public void clear() {
        youngDaoConfig.clearIdentityScope();
    }

    public youngDao getYoungDao() {
        return youngDao;
    }

}
